version: '2'

services:
  sharespace_backend:
    image: 'sharespace-spring-boot:latest'
    ports:
      - "9001:9000"
    build:
      context: .
    container_name: sharespace_springboot
    depends_on:
      - pg_database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pg_database:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  sharespace_frontend:
    image: 'sharespace-react:latest'
    ports:
      - "3001:3000"
    build:
      context: "../../../sharespace-frontend/"
      target: "frontend"
    volumes:
      - "../../../sharespace-frontend/src:/app/src"

  pg_database:
    image: 'postgres:13.1-alpine'
    container_name: pg_database
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres