name: Build, push to Docker Hub and create new Helm releases

on:
  push:
    branches: master

jobs:
  spring-boot:
    name: Docker image build and push to Docker Hub - Spring Boot app
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./ShareSpace/src/main/docker/
          file: ./ShareSpace/src/main/docker/Dockerfile
          push: true
          tags: ivot2000/sharespace-backend:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  react:
    name: Docker image build and push to Docker Hub - React app
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./ShareSpace/sharespace-frontend/
          file: ./ShareSpace/sharespace-frontend/Dockerfile
          push: true
          tags: ivot2000/sharespace-frontend:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  kubernetes-spring-boot:
   name: Helm release for the Spring Boot app
   runs-on: ubuntu-latest
   needs: [spring-boot, kubernetes-postgresql]
 
   steps:
     - uses: actions/checkout@v2
     - name: Helm upgrade or install
       uses: WyriHaximus/github-action-helm3@v2
       with:
         exec: helm upgrade --install sharespace-spring-boot ./charts/sharespace-backend
         kubeconfig: '${{ secrets.KUBECONFIG }}'

  kubernetes-react:
   name: Helm release for the React app
   runs-on: ubuntu-latest
   needs: react
 
   steps:
     - uses: actions/checkout@v2
     - name: Helm upgrade or install
       uses: WyriHaximus/github-action-helm3@v2
       with:
         exec: helm upgrade --install sharespace-react ./charts/sharespace-frontend
         kubeconfig: '${{ secrets.KUBECONFIG }}'

  kubernetes-postgresql:
   name: Pod creation for the PostgreSQL database
   runs-on: ubuntu-latest
 
   steps:
     - uses: actions/checkout@v2
     - name: Apply with kubectl
       uses: danielr1996/kubectl-action@1.0.0
       with:
         exec: kubectl apply -f ./kubernetes/sharespace-pgdb
         kubeconfig: '${{ secrets.KUBECONFIG }}'

  kubernetes-fluentd:
   name: Helm release for the Fluentd logging layer
   runs-on: ubuntu-latest
 
   steps:
     - uses: actions/checkout@v2
     - name: Helm upgrade or install
       uses: WyriHaximus/github-action-helm3@v2
       with:
         exec: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm upgrade --install fluentd bitnami/fluentd
         kubeconfig: '${{ secrets.KUBECONFIG }}'