name: Build and push to docker hub

on:
  push:
    branches: master

jobs:
  springboot:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./ShareSpace/src/main/docker/
          file: ./ShareSpace/src/main/docker/Dockerfile
          push: true
          tags: ivot2000/sharespace-backend:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  react:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./ShareSpace/sharespace-frontend/
          file: ./ShareSpace/sharespace-frontend/Dockerfile
          push: true
          tags: ivot2000/sharespace-frontend:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}